"""Create initial tables

Revision ID: 6574fe7bf885
Revises: 
Create Date: 2026-03-15 01:11:26.862618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6574fe7bf885'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finalized_bills',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('usage_kwh', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('period_start < period_end', name='ck_bill_period_order'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('login_id', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('devices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('power_kw', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)

    op.create_table('finalized_bill_members',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('finalized_bill_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('device_usage_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('equal_share_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('share_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['finalized_bill_id'], ['finalized_bills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finalized_bill_id', 'user_id')
    )
    with op.batch_alter_table('finalized_bill_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finalized_bill_members_finalized_bill_id'), ['finalized_bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finalized_bill_members_user_id'), ['user_id'], unique=False)

    op.create_table('device_usage_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),    # onupdate=func.now()がないが、今回のMVPではSQLを直接叩いたり別経路での更新は行わないのでいったんこのまま
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('end_time IS NULL OR start_time < end_time', name='ck_usage_log_time_order'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_usage_logs_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_usage_logs_start_time'), ['start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_usage_logs_start_time'))
        batch_op.drop_index(batch_op.f('ix_device_usage_logs_device_id'))

    op.drop_table('device_usage_logs')
    with op.batch_alter_table('finalized_bill_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finalized_bill_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_finalized_bill_members_finalized_bill_id'))

    op.drop_table('finalized_bill_members')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))

    op.drop_table('devices')
    op.drop_table('users')
    op.drop_table('finalized_bills')
    # ### end Alembic commands ###
